include Makefile.dependencies

# NUMERIC

$(BIN_DIR)/integer.o: $(NUM_DIR)/integer.cpp $(INTEGER_DPS)
	g++ $(FLAGS) -c $< -o $@ 

$(BIN_DIR)/rational.o: $(NUM_DIR)/rational.cpp $(RATIONAL_DPS)
	g++ $(FLAGS) -c $< -o $@ 

$(BIN_DIR)/gmp_utils.o: $(NUM_DIR)/gmp_utils.cpp $(GMP_UTILS_DPS)
	g++ $(FLAGS) -c $< -o $@ 

# DATA STRUCTURES

$(BIN_DIR)/dense_pascal_triangle.o: $(COR_DIR)/dense_pascal_triangle.cpp $(DENSE_PAS_TRI_DPS)
	g++ $(FLAGS) -c $< -o $@ -I $(NUM_DIR)

$(BIN_DIR)/sparse_pascal_triangle.o: $(COR_DIR)/sparse_pascal_triangle.cpp $(SPARSE_PAS_TRI_DPS)
	g++ $(FLAGS) -c $< -o $@ -I $(NUM_DIR)

# SYMBOLIC

$(BIN_DIR)/monomial.o: $(COR_DIR)/monomial.cpp $(MONOMIAL_DPS)
	g++ $(FLAGS) -c $< -o $@ -I $(NUM_DIR) -I $(MSC_DIR)

$(BIN_DIR)/polynomial.o: $(COR_DIR)/polynomial.cpp $(POLYNOMIAL_DPS)
	g++ $(FLAGS) -c $< -o $@ -I $(NUM_DIR) -I $(MSC_DIR)

# ALGORITHMS

$(BIN_DIR)/nested_sums.o: $(ALG_DIR)/nested_sums.cpp
	g++ $(FLAGS) -c $< -o $@ -I $(COR_DIR) -I $(NUM_DIR)

# TESTS

$(BIN_DIR)/tests.o: $(SRC_DIR)/tests.cpp $(TESTS_DPS)
	g++ $(FLAGS) -c $< -o $@ -I $(COR_DIR) -I $(NUM_DIR) -I $(MSC_DIR)
